server:
  port: 8110

spring:
  profiles:
    active: dev
  application:
    name: service-core
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33067/db_easyfunding_core?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: ''
  redis:
    host: 192.168.40.128
    port: 6379
    database: 0
    password:    #默认为空
    timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos

  rabbitmq:
    host: 192.168.40.128
    port: 15672
    virtual-host: /srbhost
    username: srbuser
    password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/atguigu/srb/core/mapper/xml/*.xml
