server:
  port: 8120

spring:
  profiles:
    active: dev
  application:
    name: service-sms

  #spring:
  redis:
    host: 192.168.100.100
    port: 6379
    database: 0
    password:
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 8
        min-idle: 0

#阿里云短信
aliyun:
  sms:
    region-id: cn-hangzhou
    key-id:
    key-secret:
    template-code:
    sign-name:
